  apiVersion: v1alpha1
  kind: AgentConfig
  rendezvousIP: 192.168.70.2
  hosts:
    - hostname: master0
      role: master
      interfaces:
       - name: ens3
         macAddress: da:b8:e4:77:82:00
      rootDeviceHints:
        minSizeGigabytes: 100
      networkConfig:
        interfaces:
          - name: ens3
            type: ethernet
            state: up
            ipv4:
              enabled: true
              address:
              - ip: 192.168.70.2
                prefix-length: 29
              dhcp: false
            ipv6:
              enabled: false
        dns-resolver:
          config:
            server:
              - 192.168.70.5
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 192.168.70.1
              next-hop-interface: ens3
              table-id: 254