  apiVersion: v1alpha1
  kind: AgentConfig
  rendezvousIP: 192.168.70.2
  hosts:
    - hostname: master0
      role: master
      interfaces:
       - name: ens3
         macAddress: da:b8:e4:77:82:00
       - name: ens4
         macAddress: 7a:61:61:0b:ef:36
      rootDeviceHints:
        deviceName: /dev/sda
      networkConfig:
        interfaces:
          - name: ens3
            type: ethernet
            state: down
            mac-address: da:b8:e4:77:82:00
          - name: ens4
            type: ethernet
            state: down
            mac-address: 7a:61:61:0b:ef:36
          - name: bond0
            type: bond
            state: up
            ipv4:
              enabled: true
              address:
              - ip: 192.168.70.2
                prefix-length: 29
              dhcp: false
            ipv6:
              enabled: false
            link-aggregation:
              mode: active-backup
              options:
                miimon: "150"
              port:
               - ens3
               - ens4
        dns-resolver:
          config:
            server:
              - 192.168.70.5
        routes:
          config:
            - destination: 0.0.0.0/0
              next-hop-address: 192.168.70.1
              next-hop-interface: bond0
              table-id: 254